### ISSUE TITLE
Add security headers

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/dxp-components#330]
## What are the acceptance criteria?

- [x] hotwax/preorder#306
- [x] hotwax/receiving#403
- [x] hotwax/order-routing#274
- [x] hotwax/fulfillment#828
- [x] hotwax/users#288
- [x] hotwax/facilities#325
- [x] hotwax/available-to-promise#383
- [x] hotwax/bopis#439
- [x] hotwax/inventory-count#480
- [x] hotwax/picking#219
- [x] hotwax/import#302
- [x] hotwax/job-manager#735
- [x] hotwax/company#47

Reference PR Link - https://github.com/hotwax/receiving/pull/372

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ashutosh7i** [comment]
Hello maintainers,
can i start working on this issue?

**Comment by ymaheshwari1** [comment]
@ashutosh7i Thanks for the interest. But this issue is not to be picked by an individual.

**Comment by ymaheshwari1** [comment]
Closing as headers are updated in all apps.
